### PR TITLE
rename action.yaml -> action.yml

### PR DESCRIPTION
**Pull request by jkremser**
before
Screenshot 2022-06-23 at 13 35 27

after (using my fork)
Screenshot 2022-06-23 at 14 08 18

required by gh actions vscode plugin to work properly

Signed-off-by: Jirka Kremser <jiri.kremser@gmail.com>

### CODE REVIEW

**Review by ytsarev — CHANGES_REQUESTED** [review]
Maybe educate vscode instead? :)

**Comment by jkremser** [comment]
> Maybe educate vscode instead? :)

I've created the issue on their side at the same time - https://github.com/cschleiden/vscode-github-actions/issues/163

The thing is that all the other gh actions we use in k8gb are just fine with the plugin, because they choose to use `action.yml` instead of `.yaml` so aligning here makes sense I think, even though we are right :D

**Review by somaritane — APPROVED** [review]

**Review by kuritka — APPROVED** [review]
it will probably take a while to update the vscode plugin. Changing "us" because of they doesn't support .yaml is not quite right, but on the other hand yml and yaml are equally valid, so I guess nothing will happen if we change the file extension.

**Review by ytsarev — APPROVED** [review]
alright, convinced :D

**Comment by jkremser** [comment]
:relieved:

**Pull request merged**
