### PR TITLE
k3d version bump 5.1.0 -> 5.2.2

### PR DESCRIPTION
**Pull request by arkadius**
Hi, I've prepared PR bumping k3d version from v5.1.0 to v5.2.2.
I've occurred some stability issues during usage of k3d-action and just want to check if this bump will help.
Should I also add new version mapping in README or it will be updated during release?

### CODE REVIEW

**Comment by kuritka** [comment]
Hi @arkadius, I really appreciate your contribution. I have several points:

 - Version mapping is not generated at the moment, the README table has to be edited manually. Tentatively the change should go to k3d-action `v2.1.0`.
- Can you please share your instability ?
- If you need to check if bump will help with instability, you should test against the forked k3d-action first.
- Our goal is to make the default versions of `k3d-action x k3d x k3s` work together as well as possible. There is also a requirement to work with the most recent versions possible. If we bump k3d, we usually also bump the default k3s.  Can you also extend your PR and test your change together with the latest stable [k3s](https://github.com/k3s-io/k3s) ? 

Thank you

**Comment by arkadius** [comment]
- I've added notice about k3d version bump in readme
- We have a several issues like: https://github.com/TouK/nussknacker/runs/4618177404?check_suite_focus=true
```
Deploy cluster k3s-default 
/usr/local/bin/k3d: line 1: syntax error near unexpected token `<'
/usr/local/bin/k3d: line 1: `﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
Error: Process completed with exit code 2.
```
or: k3d cluster was running, we can do import image to it, but after a while we've got timeout connecting to k8s cluster api: https://github.com/TouK/nussknacker/runs/4640865576?check_suite_focus=true

But all this problems were around some github actions stability incident so maybe it was temporary github actions problem.
- Regards to checking if bump will help - I haven't got option to setup k3d version in k3d-action (after releasing of #36 I will have) so then I will test if this bump will help. Do u know how to test it without releasing this version? (maybe I'm not familiar with development of github actions plugins enough)
- Regards to `k3s` version. what kind of tests you have in mind? Do u mean manual tests in our project with `image` argument or some automatic test? How this `k3s` version is fixed in `k3d-action`?

**Comment by kuritka** [comment]
Thank you for the explanation. We recently did a major refactoring so the K3s version is currently fully handled by k3d (k3d is trying to [fetch latest stable k3s of hardcoded version](https://github.com/rancher/k3d/blob/main/version/version.go#L40-L42)) and can be set explicitly via its yaml configuration or via arguments. 

Can you please edit the table and use `v1.21.7-k3s1` for k3d `v5.2.2` ? Would be good for users to let them quickly know, what k3s version is default for v5.2.2 and they will [change in config](https://k3d.io/v5.0.0/usage/configfile/) if needed.

**Comment by arkadius** [comment]
Ok, I got it - changed. I was surprised because this version is lower than for k3d `5.1.0`. I've checked hardcoded version for this tag: https://github.com/rancher/k3d/blob/v5.1.0/version/version.go#L41 and it is some strange, not existing version: https://github.com/k3s-io/k3s/releases/tag/v1.21.4%2Bk3s2 . Do you know why it is that way?

**Review by kuritka — APPROVED** [review]

**Comment by kuritka** [comment]
@arkadius This is being managed by k3d. You might have read it in the release notes.

**Pull request merged**
