### PR TITLE
Bump to k3s v1.20.5+k3s1

### PR DESCRIPTION
**Pull request by ninuxio**

### CODE REVIEW

**Comment by ninuxio** [comment]
https://github.com/k3s-io/k3s/releases/tag/v1.20.5%2Bk3s1

thanks for this action

Hope this will help

I'm not sure about 1.4.0 version tag

regards

**Review by k0da — CHANGES_REQUESTED** [review]
I don't think it is worth to bump version here

**Comment by k0da** [comment]
@ninuxio any particular fix you're looking for in 1.20.5?

**Comment by ninuxio** [comment]
Nope I just want to match my k3s ci version with my k3s prod cluster version. ;)

I can leave with my fork in the meantime.

**Comment by ninuxio** [comment]
@k0da I have reverted my changes on the readme file

**Review by k0da — APPROVED** [review]
LGTM

**Comment by kuritka** [comment]
Hi @ninuxio, thx for PR, good job! We have an issue for that (#19) requested by @eshepelyuk.
If you don't mind, I'd like to provide the ability to customize any k3s version as it is mentioned in the issue.

**Pull request closed without merging**
